[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = true
ffi = false
fs_permissions = []
offline = true
remappings = ["forge-std/=lib/forge-std/src/"]

[fuzz]
runs = 512

[fmt]
line_length = 120
